# Generated by Django 5.1 on 2024-08-08 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(17),
                            django.core.validators.MaxValueValidator(25),
                        ]
                    ),
                ),
                ("course", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        max_length=200,
                        validators=[django.core.validators.MinValueValidator(100)],
                    ),
                ),
            ],
        ),
    ]
